# Theme: Catppuccin-Frappe
include				current-theme.conf

# Misc
editor 				vim
enable_audio_bell 		no

# Font
font_family      		Fira Code
bold_font        		auto
italic_font      		auto
bold_italic_font 		auto
font_size	 		12.0
font_features 			FiraCode-Retina +zero +onum

# Bottom bar
tab_bar_min_tabs		1
tab_bar_edge			bottom
tab_bar_style			powerline
tab_powerline_style 		round
tab_title_template 		"{title}"
active_tab_title_template 	"{num_windows}:: {title}"

# Window / layouts
window_padding_width 		15
hide_window_decorations 	titlebar-only
enabled_layouts 		tall:bias=50;full_size=1;mirrored=false,stack

# Remote access for VIM control
# - Use a set socket https://github.com/kovidgoyal/kitty/issues/2426
listen_on 			unix:/tmp/mykitty
allow_remote_control		yes

# Mappings
# - Remove word
map alt+backspace send_text all \x17
# - Remove line
map super+backspace send_text all \x15
# - Move to beginning
map super+left send_text all \x01
# - Move to end
map super+right send_text all \x05
# - Single click to open URL
mouse_map left click ungrabbed mouse_click_url_or_select

# Always load login shells
shell /opt/homebrew/bin/bash --login
